---
title: "Week 3 Reading Guide"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reminders from previous sections

$n$ = sample size

$\overline{x}$ = sample mean

$s$ = sample standard deviation

$\mu$ = population mean

$\sigma$ = population standard deviation

Parameter: a value summarizing a variable(s) for a population.

Statistic: a value summarizing a variable(s) for a sample.

---

# Part 1: Hypothesis Testing (Chapter 11)

## Chapter 11 Vocabulary

Hypothesis testing framework:

\vspace{0.2in}

### Section 11.1: Sex Discrimination Case Study

point estimate:

\vspace{0.2in}

hypothesis test:

\vspace{0.2in}

randomization:

\vspace{0.2in}

simulation:

\vspace{0.2in}

independent:

\vspace{0.2in}

statistic of interest / test statistic:

\vspace{0.2in}

Statistical inference:

\vspace{0.2in}

### Section 11.2: Opportunity Cost Case Study

\vspace{0.2in}

### Section 11.3: Hypothesis Testing

Hypothesis test:

\vspace{0.2in}

Null hypothesis:

\vspace{0.2in}

Alternative hypothesis:

\vspace{0.2in}

p-value:

\vspace{0.2in}

Statistically significant:

\vspace{0.2in}

## Wrap-up Review

__Hypothesis test:__ a process to determine how strong the evidence of an effect is. This procedure is also sometimes called a ‘significance test’.

General steps of a hypothesis test:

1. Frame the research question in terms of hypotheses.

2. Collect and summarize data using a test statistic.
	
3. Assume the null hypothesis is true, and simulate a null distribution for the test statistic.

4. Compare the observed test statistic to the null distribution to calculate a p-value.

5. Make a conclusion based on the p-value and write the conclusion in context.

__Null hypothesis ($H_0$):__ the skeptical perspective; no difference; no change; no effect; random chance; what the researcher hopes to prove is **wrong**.

__Alternative hypothesis ($H_A$):__ the new perspective; a difference/increase/decrease; an effect; not random chance; what the researcher hopes to prove is **correct**.

__Null value:__ the value of the parameter when we assume the null hypothesis is true (labeled as $\text{parameter}_0$).

__Null distribution:__  the simulated or modeled distribution of statistics (sampling distribution) we would expect to occur if the null hypothesis is true.

__P-value:__ probability of seeing the observed sample data, or something more extreme, assuming the null hypothesis is true.

$\implies$ Lower the p-value the stronger the evidence AGAINST the null hypothesis, suggesting the alternative hypothesis makes more sense.

__Decision:__ a determination of whether to reject or fail to reject a null hypothesis based on a p-value and a pre-set level of significance.

- If p-value $\leq \alpha$, then reject $H_0$.

- If p-value $> \alpha$, then fail to reject $H_0$.

__Significance level ($\alpha$):__ a threshold used to determine if a p-value provides enough evidence to reject the null hypothesis or not.

- Common levels of $\alpha$ include 0.01, 0.05, and 0.10.

__Statistically significant:__ results are considered statistically significant if the p-value is below the significance level.

---

# Part 2: Confidence Intervals (Chapter 12, Section 3 Only)

## 12.3: Confidence Intervals 

Confidence interval:

\vspace{0.2in}

Bootstrap sample:

\vspace{0.2in}

Sampling with replacement:

\vspace{0.2in}

## Wrap-up Review

__Confidence interval:__ a process to determine how large an effect is; a range of plausible values for the population parameter.

__Margin of error:__ the value that is added to and subtracted from the sample statistic to create a confidence interval; half the width of a confidence interval.

__Bootstrapping:__ the process of drawing with replacement $n$ times from the original sample.

__Bootstrapped resample:__ a random sample of size $n$ from the original sample, selected with replacement.

__Bootstrapped statistic:__ the statistic recorded from the bootstrapped resample.

__Confidence level:__ how confident we are that the confidence interval will capture the population parameter.

__Bootstrap $X$% confidence interval:__ ($(\frac{(1-X)}{2})^{th}$ percentile, $(X+(\frac{(1-X)}{2})^{th}$ percentile) of a bootstrap distribution.

---

# Part 3: Inference for One Mean (Chapter 19)

## Section 19.1: Bootstrap Confidence Interval for a Mean

__In the Awesome Auto example,__

- What is the unit of study?

\vspace{0.2in}

- What was the sample mean? 

\vspace{0.2in}

- What sample size of cars was collected?

\vspace{0.2in}

- What was the standard deviation of the sample?

\vspace{0.2in}

#### 19.1.2

How is a bootstrap sample similar to collecting a new sample from the
population?

\vspace{0.2in}

How is a bootstrap sample different from collecting a new sample from the
population?

\vspace{0.2in}

To create a bootstrap distribution, for the Awesome Autos, how many cards will
you need and how will the cards be labeled?

\vspace{0.2in}

What do you do with the cards after labeling them?

\vspace{0.2in}

After resampling, what value will be plotted on the bootstrap distribution?

\vspace{0.2in}

What was the 95% confidence interval obtained with the 1000 bootstrap samples?

\vspace{0.2in}

How do you interpret this confidence interval in the context of the data?

\vspace{0.2in}

What percentiles were used to construct a 95% confidence interval?

\vspace{0.2in}

__What percentiles would you have used if you wanted a 90% confidence interval?

\vspace{0.2in}

#### 19.1.3

When can you use the SE method to create a confidence interval?
*Hint: What does this distribution need to look like?*

\vspace{0.2in}

Where does the $2$ in the $2\times SE$ method come from?

\vspace{0.2in}

Standard error:

\vspace{0.2in}

Standard deviation:

\vspace{0.2in}

Where the percentile and SE confidence intervals similar?

\vspace{0.2in}

Why do you believe this was the case?

\vspace{0.2in}

#### 19.1.4

Why would it have been inappropriate to use the SE method to find a confidence
interval for the standard deviation?

\vspace{0.2in}

True or false: Bootstrapping can only be used if the sample size is small.

\vspace{0.2in}

### Section 19.2: Mathematical Model for a Mean

**Conditions to use the CLT for means:**

- Independence: 

\vspace{0.2in}

  * Checked by: 

\vspace{0.2in}

- Normality:

\vspace{0.2in}

  * Checked by:

\vspace{0.2in}

What is a "rule of thumb" that you can use to check the normality condition?

\vspace{0.2in}

#### 19.2.3

__$t$-distribution:__

\vspace{0.2in}

How is the $t$-distribution different from the Normal distribution?

\vspace{0.2in}

How do we calculate degrees of freedom for the $t$-distribution?

\vspace{0.2in}

#### Formulas

$SE(\overline{x})=$

\vspace{0.2in}

$t^*$:

\vspace{0.2in}
 
Margin of error:

\vspace{0.2in}

Confidence interval for a mean:

\vspace{0.2in}

#### 19.2.5

$T=$

\vspace{0.2in}

How do you get a p-value for the $T$ statistic you calculate?

\vspace{0.2in}
