---
title: 'Week 7 Wednesday Reading Guide: Exploring Categorical Data'
output:
  word_document: default
  pdf_document: default
---

## Chapter 4: Exploring Categorical Data

\vspace{0.25in}

### Section 4.1: Contingency tables and bar plots

\vspace{0.25in}

**Contingency table:**

\vspace{0.25in}
\vspace{0.25in}

**Row total:**

\vspace{0.25in}

**Column total:**

\vspace{0.25in}
\vspace{0.25in}

**Frequency table:**

\vspace{0.25in}
\vspace{0.25in}

**Bar plot:**

\vspace{0.25in}
\vspace{0.25in}

**How is a bar plot similar to a histogram?**

\vspace{0.25in}
\vspace{0.25in}

**How is a bar plot different from a histogram?**

\vspace{0.25in}
\vspace{0.25in}

## Section 4.2: Visualizing two categorical variables

**What are the three ways to add a second categorical variable to a bar plot?**

\vspace{0.25in}
\vspace{0.25in}

**Which plot would be best if you wanted to compare the proportions between two 
groups?**

\vspace{0.25in}
\vspace{0.25in}

**Which plot would be best if you wanted to compare the sample size of each 
group?**

\vspace{0.25in}
\vspace{0.25in}

**Which plot would be best if one categorical variable is the response and the
other is the explanatory variable?**

\vspace{0.25in}
\vspace{0.25in}

**How is a mosaic plot different from a bar plot?**

\vspace{0.25in}
\vspace{0.25in}


## Setion 4.3: Row and column proportions

**Row proportions:**

\vspace{0.25in}
\vspace{0.25in}

**Column proportions:**

\vspace{0.25in}
\vspace{0.25in}

**Table 4.3 is called a "relative frequency table." How is this table different 
from the contingency table (Table 4.1)?**

\vspace{0.25in}
\vspace{0.25in}

**Conditional proportion:**

\vspace{0.25in}
\vspace{0.25in}

## Questions to Consider 

In a contingency table, which variable (explanatory or response) generally will
make the columns of the table?  Which variable will make the rows of the table?

\vspace{0.25in}
\vspace{0.25in}

In a segmented bar plot, the bars represent the levels of which variable?  The
segments represent the levels of which variable?

\vspace{0.25in}
\vspace{0.25in}

What type of plot(s) are appropriate to display a single categorical variable?

\vspace{0.25in}
\vspace{0.25in}

What type of plot(s) are appropriate to display two categorical variables?

\vspace{0.25in}
\vspace{0.25in}

What is the difference between a standardized segmented bar plot and a mosaic
plot?

\vspace{0.25in}
\vspace{0.25in}

True or false: Pie charts are generally highly recommended ways to graphically
display categorical data.

\vspace{0.25in}

True or false: Two categorical variables are associated if the conditional 
proportions of a particular outcome (typically of the response variable) differ
across levels of the other variable (typically the explanatory variable).

\vspace{0.25in}


True or false: When a segmented bar plot has segments that sum to 1 (or 100%),
the segment heights correspond to the proportions conditioned on the
**segment**.

\vspace{0.25in}
\vspace{0.25in}