---
title: "Week 9 Reading Guide"
output: pdf_document
# output: word_document
---
# Chapter 18: Inference for Two-Way Tables

## 18.1: Randomization test of independence

**What does the null hypothesis assume about the probability of the seller disclosing the problem?**

\vspace{0.25in}

**Under the null hypothesis does this probability differ based on the question that the buyer asked?**

\vspace{0.25in}
\vspace{0.25in}

**What did the researchers define a "success" in the iPod study?**

\vspace{0.25in}

### 18.1.1 -- Expected Counts

**Based on Table 18.1, how was the proportion of $61 / 219$ found? What does this proportion represent?** 

\vspace{0.25in}
\vspace{0.25in}

**If there had been 85 people in the "Negative assumption" group, what would be the expected counts for "Disclose problem" and "Hide problem"?**

\vspace{0.25in}
\vspace{0.25in}

**What is the general formula for calculating the expected count of a specific cell in a two-way table?**

\vspace{0.25in}
\vspace{0.25in}

### 18.1.2 -- The chi-squared statistic

**What is the formula for calculating *one* cell's contribution to the chi-squared statistic?**

\vspace{0.25in}
\vspace{0.25in}

### 18.1.3 -- Variability of Statistic

If the null hypothesis was true, we are assuming that the seller would disclose the problem with the iPod the same proportion of the time, regardless of the question that the buyer asked. 

The book doesn't cover this explicitly, but I'd like for you to think about how you could use cards to simulate what $X^2$ statistics could have happened if the null was true. 

**Step 1:** Write the outcome (disclose / hide) and the question (general /positive assumption / negative assumption) on a card. 

**How many cards will there be total?**

\vspace{0.25in}
\vspace{0.25in}

**Step 2:** Assume the null hypothesis is true and....

**What will be done with the cards?**

\vspace{0.25in}
\vspace{0.25in}

**Step 3:** Generate a new sample that could have happened if the null was true by....

**How will a new sample be made with the cards?**

\vspace{0.25in}
\vspace{0.25in}

**Step 4:** Calculate the simulated....

**What statistic will be calculated from the new sample?**

\vspace{0.25in}
\vspace{0.25in}

### 18.1.4 -- Observed Statistic vs. Null Statistics

**For an observed statistic like what is seen in Figure 18.1, what would be the approximate p-value?**

\vspace{0.25in}

**What does the p-value you stated above *mean* in the context of the observed
statistic and the null distribution?**

\vspace{0.25in}
\vspace{0.25in}

---

## 18.2 -- Mathematical Model for Test of Independence

Based on Figure 18.2, complete the following sentence: 

**As the degrees of freedom for a Chi-Squared distribution get larger, the shape of the distribution gets less...**

### 18.2.2 -- Variablity of the Chi-Squared Statistic

**What two conditions are required to be checked to use the Chi-Squared distribution to obtain a p-value?**

\vspace{0.25in}
\vspace{0.25in}

**Which of these conditions is required *regardless* of the method you use to find the p-value (simulation-based or theory-based)?**

\vspace{0.25in}
\vspace{0.25in}

**True or false: The formula for finding the $X^2$ statistic is the same for both simulation-based (randomization) and theory-based (mathematical) methods.**
