---
title: "Thinking Statistically + Data"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
---

## Friday, September 27th
### Today we will...

+ Introduce basic statistical terminology
+ Example 1.1: Alleged Hearing Loss
+ Example 1.2: Helper vs. Hinderer

::: callout-warning
#### Note that
I am traveling to MN over the weekend for a wedding. I should be back Sunday evening, but watch Canvas announcements in case my flights get severely messed up.
:::

## To do:

+ **Lab 0: Setting up posit Cloud**
  + Due (as groups) Monday 9/30 at 11:59pm
+ **Print/Download Chapter 2 Course Notes**
  + For class Tuesday 10/1
+ **Homework 1: Tidy Data and Simulation Studies**
  + Due Thursday 10/3 at 11:59pm
  
::: callout-warning
Don't forget to take the Canvas Quiz **AND** submit your completed assignment.
:::

## Monday, September 30th
### Today we will...

+ Recap basic statistical terminology
+ Example 1.3: Are women passed over for managerial training? (in groups)
+ Example 1.4: Font Preferences (in groups)
<!-- + **Exit ticket!** -->

<!-- ## Exit Ticket! `join.pd` -->

<!-- **Example 1.4: Font Preferences** -->

<!-- "Why was it important for the researchers to present balance out the order in which the fonts were presented across the study? For example, how would the study results have been affected if the researchers always presented the Signet font on the left?" -->

## To do:

+ **Lab 0: Setting up posit Cloud**
  + Due (as groups) Monday 9/30 at 11:59pm
+ **Print/Download Chapter 2 Course Notes**
  + For class Tuesday 10/1
+ **Homework 1: Tidy Data and Simulation Studies**
  + Due Thursday 10/3 at 11:59pm
+ **Review notes for Quiz 1**
  + Friday 9/4
  
<!-- ## Tuesday, October 1st -->

<!-- + Ch. 2 -- Setting up Hypotheses -->

<!-- ## To do: -->

<!-- + **Print/Download Chapter 2 Course Notes** -->
<!--   + For class Tuesday 10/1 -->
<!-- + **Homework 1: Can chimpanzees solve problems?** -->
<!--   + Due Thursday 10/3 at 11:59pm -->
<!-- + **Review notes for Quiz 1** -->
<!--   + Friday 9/4 -->

<!-- ## Thursday, October 3rd -->
<!-- ### Today we will... -->

<!-- + Lab 1: Working with Data in R -->

<!-- ## To do: -->

<!-- + **Lab 1: Working with Data in R** -->
<!--   + Due Monday 10/7 at 11:59pm -->
<!-- + **Review notes for Quiz 1** -->
<!--   + In-class Friday 9/29 -->

<!-- ## Friday, October 4th -->
<!-- ### Today we will... -->

<!-- + Quiz 1 (20 minutes to complete) -->
<!-- + Ch. 2 -- Evaluating evidence using p-values -->

<!-- ## To do: -->

<!-- + **Lab 1: Working with Data in R** -->
<!--   + Due Monday 10/7 at 11:59pm -->
<!-- + **Work on Examples 2.1 & 2.2** -->
<!--   + Will be reviewed first half of class on Monday -->