---
title: "Chapter 3: Inference for a Categorical Variable with More than Two Categories"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
---

## Monday, October 14th
### Today we will...

+ Start Ch. 3 Notes
  + Setup Example 3.1
  + Simulate outcomes and summarize
  
**New groups! Share what makes it feel like fall to you.**

## To do:

+ **Lab 2: What Impacts Strength of Evidence?**
  + Due TONIGHT 10/14 at 11:59pm
  
+ **Quiz 2: Statistical Inference for Single Proportions**
  + In class Tuesday 10/15
  
+ **Homework 3: Which cow breeds have mastitis?**
  + Due Thursday 10/17 at 11:59pm

## Tuesday, October 15th
### Today we will...

+ Quiz 2 (15 minutes)
+ Finish Ch. 3 Notes
  + Introduce Chi-square test statistic
  + Chi-square distribution

## To do:
  
+ **Homework 3: Which cow breeds have mastitis?**
  + Due Thursday 10/17 at 11:59pm
  
+ **Print/Download Chapter 4 Course Notes**
  + For class Friday 10/18

*Bring computer charged for class on Thursday.*
  
## Thursday, October 17th
### Today we will...

+ Finish Ch. 3 Chi-square Goodness of Fit Test
+ Lab 3: Is the census report accurate?
+ *Participation (P4): Tell me your group role this week when I come around during lab work time.*

## To do:
  
+ **Homework 3: Which cow breeds have mastitis?**
  + Due Friday 10/18 at 11:59pm
  
+ **Lab 3: Is the census report accurate?**
  + Due Monday 10/21 at 11:59pm
  
+ **Print/Download Chapter 4 Course Notes**
  + For class Friday 10/18

## Friday, October 18th
### Today we will...

+ *Entry Ticket (P5): What is one concept you have a question about?* -- [joinpd.com](https://app.peardeck.com/join)
+ Policy Reminder
+ Ch. 4 Notes
  + Explanatory and Response Variables
  + Visualizing and Summarizing Two Variables
+ Lab 3 + Homework 3 work time

## Policy Reminder

+ Participation (5%) -- drop 3 lowest ("sick days")
  + Expectation to come to class and arrive on time
+ Grace Days -- 24 hours to turn an Assignments, Lab, or Quiz late
  + Canvas deducts 20% per day after this
+ You should get 2 attempts at Canvas Homework Quizzes

*Be double checking your grades! These are your responsibility to keep track of and letting me know if something does not look right. I will make mistakes.*

## To do:

+ **Homework 3: Which cow breeds have mastitis?**
  + Due TONIGHT 10/18 at 11:59pm
+ **Lab 3: Is the census report accurate?**
  + Due Monday 10/21 at 11:59pm
+ **Study for Midterm Exam 1**
  + In class Tuesday 10/22
  + See Canvas for "What to Expect + Review Guide"
  
  
