---
title: "Chapter 5: Methods for Describing a Single Numerical Variable"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Monday, October 28th
### Today we will...

+ Return Midterm Exams
  + Average of 69% across three sections
  + Solutions posted to Canvas
  + Please compare your exam to the solutions, then discuss with Dr. Robinson during office hours
+ Ch. 5: Describing Numeric Variables (in groups)
  + Finish for tomorrow

## To do:

+ **Homework 4: Fatal Injuries in the Iliad**
  + Due Thursday 10/31 at 11:59pm

+ **Print Chapter 6 Notes**
  + For class Tuesday

## Tuesday, October 29th
### Today we will...

+ Review:
  + Ch. 5 -- Describing Numeric Variables
+ Distribution of the Sample Mean
+ Central Limit Theorem *(complete activity for participation credit)*

## To do:

+ **Homework 4: Fatal Injuries in the Iliad**
  + Due Thursday 10/31 at 11:59pm
  
*Bring your computers charged for Lab 4 on Thursday.*

## Thursday, October 31st
### Today we will...

+ Grab a piece of Halloween candy!
+ Lab 4: Nightlights and Myopia
  + Chi-square Test of Independence

## To do:

+ **Homework 4: Fatal Injuries in the Iliad**
  + Due TONIGHT 10/31 at 11:59pm
  
+ **Lab 4: Nightlights and Myopia**
  + Due Monday 11/4 at 11:59pm
  
+ **Print Ch. 7 Notes**
  + For class on Tuesday
