---
title: "Chapter 6: Inference for a Single Numerical Variable"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Friday, November 1st
### Today we will...

+ Review:
  + Central Limit Theorem
+ Introduce t-test
+ *P8: Exit Ticket*
  
## To do:
  
+ **Lab 4: Nightlights and Myopia**
  + Due Monday 11/4 at 11:59pm

+ **P9: Final Group Formation Survey**
  + Due Tuesday 11/5 at 11:59pm

+ **Print Ch. 7 Notes**
  + For class on Tuesday

## Monday, November 4th
### Today we will...

+ Review:
  + CLT + t-test
+ Example 6.3: Confidence Intervals
+ [KaHoot: Confidence Intervals](https://create.kahoot.it/share/cal-poly-stat-218-confidence-intervals/de7fa693-2b3d-468f-89bb-f0f29412a67e)

## To do:
  
+ **Lab 4: Nightlights and Myopia**
  + Due TONIGHT 11/4 at 11:59pm

+ **P9: Final Group Formation Survey**
  + Due Tuesday 11/5 at 11:59pm
  
+ **Homework 6: What is the average body temperature?**
  + Due Thursday 11/7 at 11:59pm
  
+ **Print Ch. 7 Notes**
  + For class on Tuesday

+ **Study for Quiz 3: Inference for a Single Numerical Variables**
  + In class Friday, 11/8
  
## Tuesday, November 5th

+ Review:
  + Examples 6.1 + 6.2
+ Ch. 7: Introduce Two-sample Independent t-test
  + Example 7.1
  + Practice, Example 7.2 (in groups)

## To do:
  
+ **P9: Final Group Formation Survey**
  + Due TONIGHT 11/5 at 11:59pm
  
+ **Homework 6: What is the average body temperature?**
  + Due Thursday 11/7 at 11:59pm
  
+ **Study for Quiz 3: Inference for a Single Numerical Variables**
  + In class Friday, 11/8
  
## Thursday, November 7th

+ Lab 6: Hours worked

## To do:
  
+ **Homework 6: What is the average body temperature?**
  + Due TONIGHT 11/7 at 11:59pm
  
+ **P13: Finish Example 7.1**
  + Checked for completion in class tomorrow
  
+ **Study for Quiz 3: Inference for a Single Numerical Variables**
  + In class Friday, 11/8
  
+ **Lab 6: Hours worked**
  + Due Monday 11/11 at 11:59pm
  
## Friday, November 8th
### Today we will...

+ Quiz 3: Inference for a Single Numerical Variable (20 minutes)
+ Group Project
  + Form New Groups
  + Introduce Final Group Project
+ Ch. 7 Practice, Example 7.2 (in groups)

## Group Project

+ Introduce yourself to your new group
  + If you could go anywhere in the world tomorrow, where would you go and why?
  + Exchange contact info
+ All: join new group workspace; find link on Canvas groups
+ Recorder only: copy the `Final Project` template from the master work space
  + Find link on Canvas modules
  
## Group Project

+ Pick a data set of interest from the provided website.
+ Pick 2 **numeric variables**
+ Big picture -- conducting a linear regression analysis (ch. 9) on the two variables (aka, is there a relationship -- think scatterplot!).

## To do:
  
+ **Lab 6: Hours worked**
  + Due Monday 11/11 at 11:59pm

+ **Work through Example 7.2** for class on Tuesday 11/12
  
+ **P10: Group Contract**
  + Due Wednesday, 11/13 at 11:59pm
  
+ **P11: Group Project Check Point 1: Data Set + Variable Selection**
  + Due Thursday, 11/21 at 11:59pm
  + The sooner you get it in, the sooner Dr. Robinson will give feedback


  
