---
title: "Chapter 9: Simple Linear Regression"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Monday, December 2nd
### Today we will...

+ Ch. 9 Notes: EDA for two numeric variables

## To do:
  
+ **Lab 8: Soil Moisture and Early Growth Biomass for Strawberries**
  + Due Tuesday 12/3 at 11:59pm
  
+ **P12: Group Project Checkpoint 2 (Histograms + Scatterplot)**
  + Due Tuesday 12/3 at 11:59pm
  
+ **Quiz 4: ANOVA** (On Canvas: 20 minutes + 1 attempt)
  + Due Tuesday 12/3 at 11:59pm

## Tuesday, December 3rd
### Today we will...

+ Tips for final project
+ Finish Ch. 9 Notes: Inference for Slope

## Final Project {.scrollable}

Write in sentence + paragraph form!

+ Data Description
  + Source of data (not just CORGIS)
  + Observational unit + variables (general)
  + Your why.
  + 2 numeric variables -- units + how were they measured?
  + Which is explanatory and which is response.
  + Expected relationship.
+ Use context and units when describing the plots.
+ Edit the section headers (`## Scatterplot between EXPLANATORY VARIABLE and RESPONSE VARIABLE`).

If you have "weird points" (e.g., an Age < 0), talk to Dr. Robinson about filtering it out.

## To do:

+ **Lab 8: Soil Moisture and Early Growth Biomass for Strawberries**
  + Due Tuesday 12/3 at 11:59pm
  
+ **P12: Group Project Checkpoint 2 (Histograms + Scatterplot)**
  + Due Tuesday 12/3 at 11:59pm
  
+ **Quiz 4: ANOVA** (On Canvas: 20 minutes + 1 attempt)
  + Due Tuesday 12/3 at 11:59pm

## Thursday, December 5th
### Today we will...

+ KaHoot Review
+ Random
  + CANCEL POSIT CLOUD SUBSCRIPTION!
  + Take Course Evaluation
  + Double-check use of Grace Days
+ Project work time

## To do:

+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression

+ **Take Course Evaluation** by Friday 12/6 at 11:59pm

+ **Study for Final Exam**
  + Saturday 12/7 at 10:10am - 1pm
  + Frost Center 181-0102 (Only water allowed)

+ **Final Project Submission**
  + Due Wednesday 12/11 at 11:59pm
  + Individual Reflection due Friday 12/13 at 11:59pm

## Friday, December 6th
### Today we will...

+ Grab a Doughnut-hole
+ Random
  + CANCEL POSIT CLOUD SUBSCRIPTION!
  + Take Course Evaluation
  + Double-check use of Grace Days
+ Review/Project work time

## Finals week office hours

+ Friday 12/3 at 1pm - 2:30pm
+ Saturday 12/4 at 8:30 - 9:30am
+ Pick 1 or 2? Monday, Tuesday, or Wednesday?
  
## To do:

+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression

+ **Take Course Evaluation** by Friday 12/6 at 11:59pm

+ **Study for Final Exam**
  + Saturday 12/7 at 10:10am - 1pm
  + Frost Center 181-0102 (Only water allowed)

+ **Final Project Submission**
  + Due Wednesday 12/11 at 11:59pm
  + Individual Reflection due Friday 12/13 at 11:59pm

